apiVersion: apps/v1
kind: Deployment
metadata:
  name: critical-app-deployment
  labels:
    app: critical-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: critical-app
  template:
    metadata:
      labels:
        app: critical-app
    spec:
      priorityClassName: high-priority # Reference the defined PriorityClass
      containers:
      - name: critical-container
        image: nginx:latest
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
