---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
value: 1000000
globalDefault: false
description: "This PriorityClass should be used for critical applications."
preemptionPolicy: PreemptLowerPriority
