apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-resource-quota
  namespace: my-namespace
spec:
  hard:
    requests.cpu: "50m" 
    requests.memory: "100Mi" 
    limits.cpu: "1"
    limits.memory: "500Mi"
    pods: "5" 
