apiVersion: v1
kind: Pod
metadata:
  name: nfs-server
spec:
  containers:
  - name: nfs-server
    image: k8s.gcr.io/volume-nfs:0.8
    ports:
    - containerPort: 2049
    volumeMounts:
    - name: nfs-volume
      mountPath: /exports
  volumes:
  - name: nfs-volume
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-service
spec:
  selector:
    app: nfs-server
  ports:
  - protocol: TCP
    port: 2049
    targetPort: 2049